---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: bnizh/api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: api
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_RELAY_PORT
          value: "61613"  
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "password"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: GRPC_CORE_SERVICE_HOST
          value: "core-service" 
        - name: GRPC_CORE_SERVICE_PORT
          value: "8080" 
        - name: GRPC_CORE_SERVICE_NEGOTIATION_TYPE
          value: "plaintext"
        - name: REDIS_HOST
          value: "redis" 
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: "redis" 