---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
  - name: consumer
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: bnizh/consumer
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "password"
        - name: GRPC_CORE_SERVICE_HOST
          value: "core-service" 
        - name: GRPC_CORE_SERVICE_PORT
          value: "8080" 
        - name: GRPC_CORE_SERVICE_NEGOTIATION_TYPE
          value: "plaintext"
        - name: YOUTUBE_KEY
          value: "AIzaSyDofjML1cjSur0nDkkExra4gAkswl-VvqI"      