---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    app: core
  ports:
  - name: core
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  selector:
    matchLabels:
      app: core
  replicas: 1
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: bnizh/core
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: GRPC_PORT
          value: "8080"  
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "password"